
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EP_Doc
{

    public int ID { get; set; }

    public Nullable<int> IDProtocol { get; set; }

    public string Name { get; set; }

    public string Path { get; set; }

    public Nullable<bool> Visible { get; set; }

    public string ContentType { get; set; }

    public string NameFile { get; set; }

    public string extension { get; set; }



    public virtual EP_Protocols EP_Protocols { get; set; }

}

}
