
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EP_Email
{

    public int ID { get; set; }

    public string Email { get; set; }

    public string Type { get; set; }

    public string NameAdress { get; set; }

}

}
