
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EP_Log
{

    public int ID { get; set; }

    public Nullable<int> IDProtocol { get; set; }

    public Nullable<int> IDVeryf { get; set; }

    public Nullable<short> UserID { get; set; }

    public Nullable<int> ServiceID { get; set; }

    public string Result { get; set; }

    public string Description { get; set; }

    public System.DateTime Date { get; set; }

    public int IDStep { get; set; }

    public string TOPBOT { get; set; }

    public Nullable<int> DocumentID { get; set; }

    public Nullable<int> LOTID { get; set; }

    public Nullable<byte> line { get; set; }

    public Nullable<short> Iter { get; set; }



    public virtual EP_Protocols EP_Protocols { get; set; }

    public virtual EP_Service EP_Service { get; set; }

    public virtual FAS_Users FAS_Users { get; set; }

    public virtual EP_TypeVerification EP_TypeVerification { get; set; }

}

}
