
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EP_Protocols
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EP_Protocols()
    {

        this.EP_Doc = new HashSet<EP_Doc>();

        this.EP_Log = new HashSet<EP_Log>();

        this.EP_PGName = new HashSet<EP_PGName>();

        this.EP_ProtocolsInfo = new HashSet<EP_ProtocolsInfo>();

    }


    public int ID { get; set; }

    public System.DateTime DateCreate { get; set; }

    public int LOTID { get; set; }

    public bool TOPBOT { get; set; }

    public bool StartStatusTOP { get; set; }

    public Nullable<bool> StartStatusBOT { get; set; }

    public string NameProtocol { get; set; }

    public bool IsActiveBOT { get; set; }

    public bool IsActiveTOP { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_Doc> EP_Doc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_Log> EP_Log { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_PGName> EP_PGName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_ProtocolsInfo> EP_ProtocolsInfo { get; set; }

}

}
