
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EP_TypeVerification
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EP_TypeVerification()
    {

        this.EP_Log = new HashSet<EP_Log>();

        this.EP_ProtocolsInfo = new HashSet<EP_ProtocolsInfo>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public string Manufacter { get; set; }

    public short Num { get; set; }

    public string TOPBOT { get; set; }

    public Nullable<int> IDService { get; set; }

    public Nullable<int> TypeDocID { get; set; }

    public string Description { get; set; }

    public Nullable<short> Sort { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_Log> EP_Log { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_ProtocolsInfo> EP_ProtocolsInfo { get; set; }

    public virtual EP_Service EP_Service { get; set; }

    public virtual EP_TypeDocument EP_TypeDocument { get; set; }

}

}
