
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FAS_Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FAS_Users()
    {

        this.FAS_GS_LOTs = new HashSet<FAS_GS_LOTs>();

        this.FAS_GS_LOTs1 = new HashSet<FAS_GS_LOTs>();

        this.EP_Log = new HashSet<EP_Log>();

        this.EP_ProtocolsInfo = new HashSet<EP_ProtocolsInfo>();

    }


    public short UserID { get; set; }

    public string RFID { get; set; }

    public string UserName { get; set; }

    public bool IsActiv { get; set; }

    public byte UsersGroupID { get; set; }

    public Nullable<int> IDService { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FAS_GS_LOTs> FAS_GS_LOTs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FAS_GS_LOTs> FAS_GS_LOTs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_Log> EP_Log { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EP_ProtocolsInfo> EP_ProtocolsInfo { get; set; }

}

}
