

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PDUManagment.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FASEntities : DbContext
{
    public FASEntities()
        : base("name=FASEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<EP_Service> EP_Service { get; set; }

    public virtual DbSet<FAS_GS_LOTs> FAS_GS_LOTs { get; set; }

    public virtual DbSet<FAS_Users> FAS_Users { get; set; }

    public virtual DbSet<CT_Сustomers> CT_Сustomers { get; set; }

    public virtual DbSet<EP_Log> EP_Log { get; set; }

    public virtual DbSet<EP_Protocols> EP_Protocols { get; set; }

    public virtual DbSet<EP_ProtocolsInfo> EP_ProtocolsInfo { get; set; }

    public virtual DbSet<EP_Result> EP_Result { get; set; }

    public virtual DbSet<EP_TypeDocument> EP_TypeDocument { get; set; }

    public virtual DbSet<EP_TypeVerification> EP_TypeVerification { get; set; }

    public virtual DbSet<EP_Doc> EP_Doc { get; set; }

    public virtual DbSet<EP_Machine> EP_Machine { get; set; }

    public virtual DbSet<EP_PGName> EP_PGName { get; set; }

    public virtual DbSet<FAS_Models> FAS_Models { get; set; }

    public virtual DbSet<Contract_LOT> Contract_LOT { get; set; }

    public virtual DbSet<EP_FileTypeMIME> EP_FileTypeMIME { get; set; }

    public virtual DbSet<EP_Email> EP_Email { get; set; }

    public virtual DbSet<FAS_Objective> FAS_Objective { get; set; }

}

}

